<?php

/**
 * @file
 * Page Load Progress allows you to set a screen lock showing a spinner when
 * the user clicks on an element that triggers a time consuming task.
 */

/**
 * Implements hook_permission().
 */
function page_load_progress_permission() {
  return array(
    'administer Page Load Progress settings' => array(
      'title' => t('Administer Page Load Progress settings'),
    ),
  );
}

/**
 * Implements hook_page_build().
 */
function page_load_progress_page_build(&$page) {
  $path = drupal_get_path('module', 'page_load_progress');
  $page['#attached']['js'][$path . '/js/page_load_progress.js'] = array('every_page' => TRUE);
}
